"""Synthetic Speakeasy MCP tool files + a matching OpenAPI spec for the tests.

We intentionally do NOT snapshot the real ``calibrate-mcp`` tool files — that
drifts and would pin tests to upstream wording. Instead these hand-built samples
exercise every parsing/rendering variation the generator must handle:

- a read-only tool with a single path parameter;
- a write tool whose body is a ``$ref`` object (required + optional props);
- a write tool whose body is ``anyOf: [Ref, null]`` (an optional request body);
- a read-only tool with no arguments at all;
- a multi-line ``description`` template literal (collapsed to one line in tables);
- a non-tool file (no ``name:``) that must be skipped.

The OpenAPI spec below is self-consistent with the tool files: each tool's
``models/<stem>.js`` import equals ``operation_key(operationId)`` for one of
these operations, so the generator can match them.

The live server is validated separately by the sync workflow.
"""

from __future__ import annotations

from pathlib import Path

# --- tool files (src/mcp-server/tools/*.ts) -------------------------------- #

LIST_WIDGETS_TS = '''/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { widgetsList } from "../../funcs/widgetsList.js";
import { ListWidgetsWidgetsGetRequest$zodSchema } from "../../models/listwidgetswidgetsgetop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {};

export const tool$widgetsList: ToolDefinition<typeof args> = {
  name: "list-widgets",
  description:
    `List every widget in the caller's org. Returns each widget's UUID and
name.
`,
  scopes: ["read"],
  annotations: {
    "title": "List widgets",
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": true,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {},
};
'''

CREATE_WIDGET_TS = '''/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { widgetsCreate } from "../../funcs/widgetsCreate.js";
import { CreateWidgetWidgetsPostRequest$zodSchema } from "../../models/createwidgetwidgetspostop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateWidgetWidgetsPostRequest$zodSchema,
};

export const tool$widgetsCreate: ToolDefinition<typeof args> = {
  name: "create-widget",
  description:
    `Create a new widget. Provide the widget's name and optional color.
Returns the created widget.
`,
  scopes: ["write"],
  annotations: {
    "title": "Create widget",
    "destructiveHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {},
};
'''

GET_WIDGET_TS = '''/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { widgetsGet } from "../../funcs/widgetsGet.js";
import { GetWidgetWidgetsWidgetUuidGetRequest$zodSchema } from "../../models/getwidgetwidgetswidgetuuidgetop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetWidgetWidgetsWidgetUuidGetRequest$zodSchema,
};

export const tool$widgetsGet: ToolDefinition<typeof args> = {
  name: "get-widget",
  description: `Fetch a single widget by UUID.`,
  scopes: ["read"],
  annotations: {
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {},
};
'''

RUN_GADGETS_TS = '''/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { gadgetsRun } from "../../funcs/gadgetsRun.js";
import { RunGadgetsGadgetsRunPostRequest$zodSchema } from "../../models/rungadgetsgadgetsrunpostop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: RunGadgetsGadgetsRunPostRequest$zodSchema,
};

export const tool$gadgetsRun: ToolDefinition<typeof args> = {
  name: "run-gadgets",
  description: `Launch one job per gadget. Optionally restrict to gadget_names.`,
  scopes: ["write"],
  annotations: {
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {},
};
'''

# Not a tool — a shared helper file that has no ``name:`` field; must be skipped.
HELPER_TS = '''/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export function formatResult(value: unknown): string {
  return JSON.stringify(value);
}
'''

# A tool whose operation is absent from the spec — drives the unmatched guard.
ORPHAN_TS = '''import { OrphanMissingOpRequest$zodSchema } from "../../models/orphanmissingopop.js";
export const tool$orphan: ToolDefinition<typeof args> = {
  name: "orphan-tool",
  description: `A tool with no matching OpenAPI operation.`,
  scopes: ["read"],
  annotations: { "readOnlyHint": true },
};
'''

SAMPLES: dict[str, str] = {
    "widgetsList.ts": LIST_WIDGETS_TS,
    "widgetsCreate.ts": CREATE_WIDGET_TS,
    "widgetsGet.ts": GET_WIDGET_TS,
    "gadgetsRun.ts": RUN_GADGETS_TS,
    "helpers.ts": HELPER_TS,
}


def write_samples(tools_dir: Path, samples: dict[str, str] | None = None) -> Path:
    """Write the synthetic tool files into ``tools_dir`` and return it."""
    tools_dir = Path(tools_dir)
    tools_dir.mkdir(parents=True, exist_ok=True)
    for name, text in (samples or SAMPLES).items():
        (tools_dir / name).write_text(text, encoding="utf-8")
    return tools_dir


# --- matching OpenAPI spec ------------------------------------------------- #

OPENAPI: dict = {
    "openapi": "3.1.0",
    "paths": {
        "/widgets": {
            "get": {
                "operationId": "list_widgets_widgets_get",
                "tags": ["widgets"],
                "summary": "List widgets",
            },
            "post": {
                "operationId": "create_widget_widgets_post",
                "tags": ["widgets"],
                "summary": "Create widget",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {"$ref": "#/components/schemas/WidgetCreate"}
                        }
                    }
                },
            },
        },
        "/widgets/{widget_uuid}": {
            "get": {
                "operationId": "get_widget_widgets__widget_uuid__get",
                "tags": ["widgets"],
                "summary": "Get widget",
                "parameters": [
                    {
                        "name": "widget_uuid",
                        "in": "path",
                        "required": True,
                        "schema": {"type": "string"},
                        "description": "The widget to retrieve.",
                    },
                    {
                        "name": "X-API-Key",
                        "in": "header",
                        "required": True,
                        "schema": {"type": "string"},
                        "description": "auth header — must be dropped",
                    },
                ],
            },
        },
        "/gadgets/run": {
            "post": {
                "operationId": "run_gadgets_gadgets_run_post",
                "tags": ["gadgets"],
                "summary": "Run gadgets",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "anyOf": [
                                    {"$ref": "#/components/schemas/GadgetBatch"},
                                    {"type": "null"},
                                ]
                            }
                        }
                    }
                },
            },
        },
    },
    "components": {
        "schemas": {
            "WidgetCreate": {
                "type": "object",
                "required": ["name"],
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "Widget name.\nMust be unique.",
                    },
                    "color": {
                        "anyOf": [{"type": "string"}, {"type": "null"}],
                        "description": "Optional color.",
                    },
                    "tags": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Labels.",
                    },
                },
            },
            "GadgetBatch": {
                "type": "object",
                "properties": {
                    "gadget_names": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Gadgets to run. Omit to run all.",
                    }
                },
            },
        }
    },
}
